services:
  novaos-langgraph:
    container_name: novaos_langgraph
    image: python:3.11-slim
    working_dir: /app
    volumes:
      - ./langgraph:/app/langgraph
    env_file:
      - .env
    command: >
      sh -c "
        pip install --upgrade pip &&
        pip install langchain-community langchain-openai langgraph dropbox &&
        python langgraph/main.py"
    restart: unless-stopped
