name: Ingest repo docs into Memory

on:
  push:
    branches: [ "main" ]
  workflow_dispatch: {}

concurrency:
  group: ingest-memory
  cancel-in-progress: true

jobs:
  ingest:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    env:
      DATABASE_URL: ${{ secrets.DATABASE_URL_GHA }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install deps
        run: pip install --quiet "psycopg[binary]>=3.1"

      - name: Ingest docs (no git ops)
        run: python scripts/ingest_memory.py
