name: Ingest ChatGPT export into Memory

on:
  push:
    branches: [ "main" ]
    paths:
      - "brain/chatgpt_export/**"
      - "scripts/ingest_chatgpt_export.py"
      - ".github/workflows/ingest-chatgpt-export.yml"
  workflow_dispatch: {}

jobs:
  ingest:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    env:
      DATABASE_URL: ${{ secrets.DATABASE_URL_GHA }}

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install deps
        run: python -m pip install --quiet "psycopg[binary]>=3.1"

      - name: DB preflight
        run: |
          python - <<'PY'
          import os, psycopg
          db=os.environ['DATABASE_URL'].strip().replace('\n','').replace('\r','')
          if 'sslmode=' not in db:
              db += ('?sslmode=require' if '?' not in db else '&sslmode=require')
          with psycopg.connect(db) as c, c.cursor() as cur:
              cur.execute("SELECT to_regclass('public.memory_chunks');")
              assert cur.fetchone()[0], "table memory_chunks missing"
          print("DB_OK")
          PY

      - name: Ingest ChatGPT export
        run: python scripts/ingest_chatgpt_export.py
