name: Ingest Memory
on:
  push:
    branches: [ "main" ]
  workflow_dispatch: {}

concurrency:
  group: ingest-memory
  cancel-in-progress: true

jobs:
  ingest:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    env:
      DATABASE_URL: ${{ secrets.DATABASE_URL_GHA }}
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Set safe directory
        run: git config --global --add safe.directory "$GITHUB_WORKSPACE" || true
      - name: Set up Python 3.11
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - name: Install dependencies
        run: pip install "psycopg[binary]>=3.1"
      - name: Run ingest script
        run: python scripts/ingest_memory.py
