name: Ingest Memory
on:
  push:
    branches: [ "main" ]
  workflow_dispatch: {}

concurrency:
  group: ingest-memory
  cancel-in-progress: true

jobs:
  ingest:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    env:
      DATABASE_URL: ${{ secrets.DATABASE_URL_GHA }}
    steps:
      - name: Set up Python 3.11
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Ensure tools
        run: |
          sudo apt-get update -y
          sudo apt-get install -y curl unzip

      - name: Download repo as zip (no git)
        run: |
          set -e
          echo "Downloading zip for ${{ github.repository }} @ ${{ github.sha }}"
          curl -sS -H "Authorization: token ${{ github.token }}" \
               -L "https://api.github.com/repos/${{ github.repository }}/zipball/${{ github.sha }}" \
               -o src.zip
          unzip -q src.zip -d src
          REPO_DIR="$(ls -1 src)"
          echo "Unzipped folder: $REPO_DIR"
          shopt -s dotglob
          mkdir -p workspace
          mv "src/$REPO_DIR"/* workspace/
          mv "src/$REPO_DIR"/.* workspace/ || true
          rm -rf src src.zip
          ls -la workspace | sed -n '1,200p'

      - name: Check ingest script exists
        run: |
          set -e
          test -f workspace/scripts/ingest_memory.py || (echo "ERROR: workspace/scripts/ingest_memory.py not found"; find workspace -maxdepth 3 -type f | sort | sed -n '1,200p'; exit 7)

      - name: DB preflight
        run: |
          python - <<'PY'
          import os, psycopg
          db=os.environ["DATABASE_URL"]
          if "sslmode=" not in db: db+=("?sslmode=require" if "?" not in db else "&sslmode=require")
          print("DB host:", db.split("@")[1].split("/")[0])
          with psycopg.connect(db) as c, c.cursor() as cur:
              cur.execute("SELECT 1;")
              cur.execute("SELECT to_regclass('public.memory_chunks');")
              assert cur.fetchone()[0], "table memory_chunks missing"
          print("DB OK")
          PY

      - name: Install Python deps
        working-directory: workspace
        run: pip install --quiet "psycopg[binary]>=3.1"

      - name: Ingest
        working-directory: workspace
        run: |
          set -e
          python -u scripts/ingest_memory.py || (echo "INGEST_FAILED"; exit 9)
