name: Memory Index (doc_id)
on:
  workflow_dispatch: {}
  push:
    branches: [ "main" ]
    paths:
      - ".github/workflows/memory-index-docid.yml"

jobs:
  index:
    runs-on: ubuntu-latest
    env:
      DATABASE_URL: ${{ secrets.DATABASE_URL_GHA }}
    steps:
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - name: Install psycopg
        run: python -m pip install --quiet "psycopg[binary]>=3.1"
      - name: Create indexes (idempotent)
        run: |
          python - <<'PY'
          import os, psycopg
          db=os.environ["DATABASE_URL"].strip()
          if "sslmode=" not in db: db+=("?sslmode=require" if "?" not in db else "&sslmode=require")
          sql = """
          -- FTS on content (already created earlier, safe to repeat)
          CREATE INDEX IF NOT EXISTS memory_chunks_fts_idx
          ON memory_chunks USING GIN (to_tsvector('english', content));

          -- Title-aware FTS on doc_id (no extensions required)
          CREATE INDEX IF NOT EXISTS memory_chunks_docid_fts_idx
          ON memory_chunks USING GIN (to_tsvector('simple', coalesce(doc_id,'')));
          """
          with psycopg.connect(db) as c, c.cursor() as cur:
              cur.execute(sql)
          print("INDEX_OK")
          PY
